version: 2.1

cache_keys:
  - &deps_cache_key 'v1-deps-{{ checksum "package-lock-original.json" }}'

commands:
  npm_install:
    steps:
      - run: cp package-lock.json package-lock-original.json
      - restore_cache: { key: *deps_cache_key }
      - run: npm install
      - save_cache:
          key: *deps_cache_key
          paths: [ node_modules ]

jobs:
  test:
    docker:
      - image: cimg/node:14.16
    steps:
      - checkout
      - npm_install
      - run: npm test
      - run: npm run lint
      - run: npm run build

  deploy:
    docker:
      - image: cimg/node:14.16
    steps:
      - checkout
      - npm_install
      - run: npm run build
      - run:
          name: publish
          command: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" && npm publish

workflows:
  Test and Deploy:
    jobs:
      - test
      - deploy:
         requires: [test]
         filters:
           branches: { only: [ master ] }
